const ONE_MINUTE_IN_SECONDS = 60;

const ONE_HOUR_IN_SECONDS = 60 * ONE_MINUTE_IN_SECONDS;

const ONE_DAY_IN_SECONDS = 24 * ONE_HOUR_IN_SECONDS;

export const THIRTY_DAYS_IN_SECONDS = 30 * ONE_DAY_IN_SECONDS;
