/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ALenderInterface extends ethers.utils.Interface {
  functions: {
    "balance()": FunctionFragment;
    "borrow(address,uint256,uint256,address)": FunctionFragment;
    "converter()": FunctionFragment;
    "deposit(address,uint256,address)": FunctionFragment;
    "getLendingPrice(address,address)": FunctionFragment;
    "governance()": FunctionFragment;
    "priceOracle()": FunctionFragment;
    "repay(address,uint256,address)": FunctionFragment;
    "setGovernance(address)": FunctionFragment;
    "setPriceOracle(address)": FunctionFragment;
    "withdraw(address,uint256,address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "balance", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "borrow",
    values: [string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "converter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPrice",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceOracle",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "balance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "converter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {};
}

export class ALender extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ALenderInterface;

  functions: {
    balance(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "balance()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    borrow(
      _reserve: string,
      _amount: BigNumberish,
      _interestRateModel: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "borrow(address,uint256,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _interestRateModel: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    converter(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "converter()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    deposit(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "deposit(address,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    getLendingPrice(
      fromToken: string,
      toToken: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getLendingPrice(address,address)"(
      fromToken: string,
      toToken: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    governance(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "governance()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    priceOracle(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "priceOracle()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    repay(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "repay(address,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setGovernance(
      _governance: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setGovernance(address)"(
      _governance: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setPriceOracle(
      _priceOracle: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setPriceOracle(address)"(
      _priceOracle: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdraw(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdraw(address,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  balance(overrides?: CallOverrides): Promise<BigNumber>;

  "balance()"(overrides?: CallOverrides): Promise<BigNumber>;

  borrow(
    _reserve: string,
    _amount: BigNumberish,
    _interestRateModel: BigNumberish,
    _sender: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "borrow(address,uint256,uint256,address)"(
    _reserve: string,
    _amount: BigNumberish,
    _interestRateModel: BigNumberish,
    _sender: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  converter(overrides?: CallOverrides): Promise<string>;

  "converter()"(overrides?: CallOverrides): Promise<string>;

  deposit(
    _reserve: string,
    _amount: BigNumberish,
    _sender: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "deposit(address,uint256,address)"(
    _reserve: string,
    _amount: BigNumberish,
    _sender: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  getLendingPrice(
    fromToken: string,
    toToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getLendingPrice(address,address)"(
    fromToken: string,
    toToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  governance(overrides?: CallOverrides): Promise<string>;

  "governance()"(overrides?: CallOverrides): Promise<string>;

  priceOracle(overrides?: CallOverrides): Promise<string>;

  "priceOracle()"(overrides?: CallOverrides): Promise<string>;

  repay(
    _reserve: string,
    _amount: BigNumberish,
    _sender: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "repay(address,uint256,address)"(
    _reserve: string,
    _amount: BigNumberish,
    _sender: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setGovernance(
    _governance: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setGovernance(address)"(
    _governance: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setPriceOracle(
    _priceOracle: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setPriceOracle(address)"(
    _priceOracle: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdraw(
    _reserve: string,
    _amount: BigNumberish,
    _sender: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdraw(address,uint256,address)"(
    _reserve: string,
    _amount: BigNumberish,
    _sender: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    balance(overrides?: CallOverrides): Promise<BigNumber>;

    "balance()"(overrides?: CallOverrides): Promise<BigNumber>;

    borrow(
      _reserve: string,
      _amount: BigNumberish,
      _interestRateModel: BigNumberish,
      _sender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "borrow(address,uint256,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _interestRateModel: BigNumberish,
      _sender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    converter(overrides?: CallOverrides): Promise<string>;

    "converter()"(overrides?: CallOverrides): Promise<string>;

    deposit(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "deposit(address,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getLendingPrice(
      fromToken: string,
      toToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLendingPrice(address,address)"(
      fromToken: string,
      toToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<string>;

    "governance()"(overrides?: CallOverrides): Promise<string>;

    priceOracle(overrides?: CallOverrides): Promise<string>;

    "priceOracle()"(overrides?: CallOverrides): Promise<string>;

    repay(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "repay(address,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setGovernance(
      _governance: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setGovernance(address)"(
      _governance: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setPriceOracle(
      _priceOracle: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setPriceOracle(address)"(
      _priceOracle: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdraw(address,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    balance(overrides?: CallOverrides): Promise<BigNumber>;

    "balance()"(overrides?: CallOverrides): Promise<BigNumber>;

    borrow(
      _reserve: string,
      _amount: BigNumberish,
      _interestRateModel: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "borrow(address,uint256,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _interestRateModel: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    converter(overrides?: CallOverrides): Promise<BigNumber>;

    "converter()"(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "deposit(address,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    getLendingPrice(
      fromToken: string,
      toToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLendingPrice(address,address)"(
      fromToken: string,
      toToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<BigNumber>;

    "governance()"(overrides?: CallOverrides): Promise<BigNumber>;

    priceOracle(overrides?: CallOverrides): Promise<BigNumber>;

    "priceOracle()"(overrides?: CallOverrides): Promise<BigNumber>;

    repay(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "repay(address,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setGovernance(
      _governance: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setGovernance(address)"(
      _governance: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setPriceOracle(
      _priceOracle: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setPriceOracle(address)"(
      _priceOracle: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdraw(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdraw(address,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    balance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "balance()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    borrow(
      _reserve: string,
      _amount: BigNumberish,
      _interestRateModel: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "borrow(address,uint256,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _interestRateModel: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    converter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "converter()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "deposit(address,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    getLendingPrice(
      fromToken: string,
      toToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLendingPrice(address,address)"(
      fromToken: string,
      toToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    governance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "governance()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    priceOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "priceOracle()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    repay(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "repay(address,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setGovernance(
      _governance: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setGovernance(address)"(
      _governance: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setPriceOracle(
      _priceOracle: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPriceOracle(address)"(
      _priceOracle: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdraw(address,uint256,address)"(
      _reserve: string,
      _amount: BigNumberish,
      _sender: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
