/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ElfAllocatorInterface extends ethers.utils.Interface {
  functions: {
    "allocate(uint256)": FunctionFragment;
    "allocations(uint256)": FunctionFragment;
    "balance()": FunctionFragment;
    "deallocate(uint256)": FunctionFragment;
    "getAllocations()": FunctionFragment;
    "getNumAllocations()": FunctionFragment;
    "governance()": FunctionFragment;
    "pool()": FunctionFragment;
    "setAllocations(address[],address[],address[],uint256[],address[],uint256)": FunctionFragment;
    "setGovernance(address)": FunctionFragment;
    "setPool(address)": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allocate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allocations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "balance", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deallocate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllocations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNumAllocations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAllocations",
    values: [
      string[],
      string[],
      string[],
      BigNumberish[],
      string[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernance",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setPool", values: [string]): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "allocate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deallocate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumAllocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAllocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {};
}

export class ElfAllocator extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ElfAllocatorInterface;

  functions: {
    allocate(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "allocate(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    allocations(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      fromToken: string;
      toToken: string;
      lender: string;
      percent: BigNumber;
      asset: string;
      0: string;
      1: string;
      2: string;
      3: BigNumber;
      4: string;
    }>;

    "allocations(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      fromToken: string;
      toToken: string;
      lender: string;
      percent: BigNumber;
      asset: string;
      0: string;
      1: string;
      2: string;
      3: BigNumber;
      4: string;
    }>;

    balance(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "balance()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    deallocate(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deallocate(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getAllocations(
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
      1: string[];
      2: string[];
      3: BigNumber[];
      4: string[];
      5: BigNumber;
    }>;

    "getAllocations()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
      1: string[];
      2: string[];
      3: BigNumber[];
      4: string[];
      5: BigNumber;
    }>;

    getNumAllocations(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getNumAllocations()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    governance(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "governance()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    pool(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "pool()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setAllocations(
      _fromToken: string[],
      _toToken: string[],
      _lenders: string[],
      _percents: BigNumberish[],
      _asset: string[],
      numAllocations: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setAllocations(address[],address[],address[],uint256[],address[],uint256)"(
      _fromToken: string[],
      _toToken: string[],
      _lenders: string[],
      _percents: BigNumberish[],
      _asset: string[],
      numAllocations: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setGovernance(
      _governance: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setGovernance(address)"(
      _governance: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setPool(_pool: string, overrides?: Overrides): Promise<ContractTransaction>;

    "setPool(address)"(
      _pool: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdraw(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdraw(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  allocate(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "allocate(uint256)"(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  allocations(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    fromToken: string;
    toToken: string;
    lender: string;
    percent: BigNumber;
    asset: string;
    0: string;
    1: string;
    2: string;
    3: BigNumber;
    4: string;
  }>;

  "allocations(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    fromToken: string;
    toToken: string;
    lender: string;
    percent: BigNumber;
    asset: string;
    0: string;
    1: string;
    2: string;
    3: BigNumber;
    4: string;
  }>;

  balance(overrides?: CallOverrides): Promise<BigNumber>;

  "balance()"(overrides?: CallOverrides): Promise<BigNumber>;

  deallocate(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "deallocate(uint256)"(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getAllocations(
    overrides?: CallOverrides
  ): Promise<{
    0: string[];
    1: string[];
    2: string[];
    3: BigNumber[];
    4: string[];
    5: BigNumber;
  }>;

  "getAllocations()"(
    overrides?: CallOverrides
  ): Promise<{
    0: string[];
    1: string[];
    2: string[];
    3: BigNumber[];
    4: string[];
    5: BigNumber;
  }>;

  getNumAllocations(overrides?: CallOverrides): Promise<BigNumber>;

  "getNumAllocations()"(overrides?: CallOverrides): Promise<BigNumber>;

  governance(overrides?: CallOverrides): Promise<string>;

  "governance()"(overrides?: CallOverrides): Promise<string>;

  pool(overrides?: CallOverrides): Promise<string>;

  "pool()"(overrides?: CallOverrides): Promise<string>;

  setAllocations(
    _fromToken: string[],
    _toToken: string[],
    _lenders: string[],
    _percents: BigNumberish[],
    _asset: string[],
    numAllocations: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setAllocations(address[],address[],address[],uint256[],address[],uint256)"(
    _fromToken: string[],
    _toToken: string[],
    _lenders: string[],
    _percents: BigNumberish[],
    _asset: string[],
    numAllocations: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setGovernance(
    _governance: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setGovernance(address)"(
    _governance: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setPool(_pool: string, overrides?: Overrides): Promise<ContractTransaction>;

  "setPool(address)"(
    _pool: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdraw(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdraw(uint256)"(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    allocate(_amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "allocate(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    allocations(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      fromToken: string;
      toToken: string;
      lender: string;
      percent: BigNumber;
      asset: string;
      0: string;
      1: string;
      2: string;
      3: BigNumber;
      4: string;
    }>;

    "allocations(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      fromToken: string;
      toToken: string;
      lender: string;
      percent: BigNumber;
      asset: string;
      0: string;
      1: string;
      2: string;
      3: BigNumber;
      4: string;
    }>;

    balance(overrides?: CallOverrides): Promise<BigNumber>;

    "balance()"(overrides?: CallOverrides): Promise<BigNumber>;

    deallocate(_amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "deallocate(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllocations(
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
      1: string[];
      2: string[];
      3: BigNumber[];
      4: string[];
      5: BigNumber;
    }>;

    "getAllocations()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
      1: string[];
      2: string[];
      3: BigNumber[];
      4: string[];
      5: BigNumber;
    }>;

    getNumAllocations(overrides?: CallOverrides): Promise<BigNumber>;

    "getNumAllocations()"(overrides?: CallOverrides): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<string>;

    "governance()"(overrides?: CallOverrides): Promise<string>;

    pool(overrides?: CallOverrides): Promise<string>;

    "pool()"(overrides?: CallOverrides): Promise<string>;

    setAllocations(
      _fromToken: string[],
      _toToken: string[],
      _lenders: string[],
      _percents: BigNumberish[],
      _asset: string[],
      numAllocations: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAllocations(address[],address[],address[],uint256[],address[],uint256)"(
      _fromToken: string[],
      _toToken: string[],
      _lenders: string[],
      _percents: BigNumberish[],
      _asset: string[],
      numAllocations: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setGovernance(
      _governance: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setGovernance(address)"(
      _governance: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setPool(_pool: string, overrides?: CallOverrides): Promise<void>;

    "setPool(address)"(_pool: string, overrides?: CallOverrides): Promise<void>;

    withdraw(_amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "withdraw(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    allocate(_amount: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "allocate(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    allocations(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allocations(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balance(overrides?: CallOverrides): Promise<BigNumber>;

    "balance()"(overrides?: CallOverrides): Promise<BigNumber>;

    deallocate(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "deallocate(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getAllocations(overrides?: CallOverrides): Promise<BigNumber>;

    "getAllocations()"(overrides?: CallOverrides): Promise<BigNumber>;

    getNumAllocations(overrides?: CallOverrides): Promise<BigNumber>;

    "getNumAllocations()"(overrides?: CallOverrides): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<BigNumber>;

    "governance()"(overrides?: CallOverrides): Promise<BigNumber>;

    pool(overrides?: CallOverrides): Promise<BigNumber>;

    "pool()"(overrides?: CallOverrides): Promise<BigNumber>;

    setAllocations(
      _fromToken: string[],
      _toToken: string[],
      _lenders: string[],
      _percents: BigNumberish[],
      _asset: string[],
      numAllocations: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setAllocations(address[],address[],address[],uint256[],address[],uint256)"(
      _fromToken: string[],
      _toToken: string[],
      _lenders: string[],
      _percents: BigNumberish[],
      _asset: string[],
      numAllocations: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setGovernance(
      _governance: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setGovernance(address)"(
      _governance: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setPool(_pool: string, overrides?: Overrides): Promise<BigNumber>;

    "setPool(address)"(
      _pool: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdraw(_amount: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "withdraw(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allocate(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "allocate(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    allocations(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allocations(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "balance()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deallocate(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deallocate(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getAllocations(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getAllocations()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNumAllocations(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getNumAllocations()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    governance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "governance()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "pool()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setAllocations(
      _fromToken: string[],
      _toToken: string[],
      _lenders: string[],
      _percents: BigNumberish[],
      _asset: string[],
      numAllocations: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setAllocations(address[],address[],address[],uint256[],address[],uint256)"(
      _fromToken: string[],
      _toToken: string[],
      _lenders: string[],
      _percents: BigNumberish[],
      _asset: string[],
      numAllocations: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setGovernance(
      _governance: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setGovernance(address)"(
      _governance: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setPool(
      _pool: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPool(address)"(
      _pool: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdraw(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
