/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ElfContractsTestInterface extends ethers.utils.Interface {
  functions: {
    "IS_TEST()": FunctionFragment;
    "_elfDeploy()": FunctionFragment;
    "elf()": FunctionFragment;
    "failed()": FunctionFragment;
    "hevm()": FunctionFragment;
    "setUp()": FunctionFragment;
    "testFail_setGovernance()": FunctionFragment;
    "test_balance()": FunctionFragment;
    "test_balanceUnderlying()": FunctionFragment;
    "test_depositAndWithdraw()": FunctionFragment;
    "test_setGovernance()": FunctionFragment;
    "usdc()": FunctionFragment;
    "user1()": FunctionFragment;
    "user2()": FunctionFragment;
    "user3()": FunctionFragment;
    "weth()": FunctionFragment;
    "yusdc()": FunctionFragment;
    "yusdcAsset()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "IS_TEST", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "_elfDeploy",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "elf", values?: undefined): string;
  encodeFunctionData(functionFragment: "failed", values?: undefined): string;
  encodeFunctionData(functionFragment: "hevm", values?: undefined): string;
  encodeFunctionData(functionFragment: "setUp", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "testFail_setGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_balance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_balanceUnderlying",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_depositAndWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_setGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(functionFragment: "user1", values?: undefined): string;
  encodeFunctionData(functionFragment: "user2", values?: undefined): string;
  encodeFunctionData(functionFragment: "user3", values?: undefined): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;
  encodeFunctionData(functionFragment: "yusdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "yusdcAsset",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "IS_TEST", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "_elfDeploy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "elf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "failed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hevm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testFail_setGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_balance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_balanceUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_depositAndWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_setGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "user1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "user2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "user3", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yusdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yusdcAsset", data: BytesLike): Result;

  events: {
    "eventListener(address,bool)": EventFragment;
    "log_bytes32(bytes32)": EventFragment;
    "log_named_address(bytes32,address)": EventFragment;
    "log_named_bytes32(bytes32,bytes32)": EventFragment;
    "log_named_decimal_int(bytes32,int256,uint256)": EventFragment;
    "log_named_decimal_uint(bytes32,uint256,uint256)": EventFragment;
    "log_named_int(bytes32,int256)": EventFragment;
    "log_named_string(bytes32,string)": EventFragment;
    "log_named_uint(bytes32,uint256)": EventFragment;
    "logs(bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "eventListener"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_address"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "logs"): EventFragment;
}

export class ElfContractsTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ElfContractsTestInterface;

  functions: {
    IS_TEST(
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "IS_TEST()"(
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    _elfDeploy(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "_elfDeploy()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    elf(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "elf()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    failed(
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "failed()"(
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    hevm(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "hevm()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setUp(overrides?: Overrides): Promise<ContractTransaction>;

    "setUp()"(overrides?: Overrides): Promise<ContractTransaction>;

    testFail_setGovernance(overrides?: Overrides): Promise<ContractTransaction>;

    "testFail_setGovernance()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    test_balance(overrides?: Overrides): Promise<ContractTransaction>;

    "test_balance()"(overrides?: Overrides): Promise<ContractTransaction>;

    test_balanceUnderlying(overrides?: Overrides): Promise<ContractTransaction>;

    "test_balanceUnderlying()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    test_depositAndWithdraw(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "test_depositAndWithdraw()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    test_setGovernance(overrides?: Overrides): Promise<ContractTransaction>;

    "test_setGovernance()"(overrides?: Overrides): Promise<ContractTransaction>;

    usdc(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "usdc()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    user1(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "user1()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    user2(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "user2()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    user3(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "user3()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    weth(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "weth()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    yusdc(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "yusdc()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    yusdcAsset(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "yusdcAsset()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  IS_TEST(overrides?: CallOverrides): Promise<boolean>;

  "IS_TEST()"(overrides?: CallOverrides): Promise<boolean>;

  _elfDeploy(overrides?: CallOverrides): Promise<string>;

  "_elfDeploy()"(overrides?: CallOverrides): Promise<string>;

  elf(overrides?: CallOverrides): Promise<string>;

  "elf()"(overrides?: CallOverrides): Promise<string>;

  failed(overrides?: CallOverrides): Promise<boolean>;

  "failed()"(overrides?: CallOverrides): Promise<boolean>;

  hevm(overrides?: CallOverrides): Promise<string>;

  "hevm()"(overrides?: CallOverrides): Promise<string>;

  setUp(overrides?: Overrides): Promise<ContractTransaction>;

  "setUp()"(overrides?: Overrides): Promise<ContractTransaction>;

  testFail_setGovernance(overrides?: Overrides): Promise<ContractTransaction>;

  "testFail_setGovernance()"(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  test_balance(overrides?: Overrides): Promise<ContractTransaction>;

  "test_balance()"(overrides?: Overrides): Promise<ContractTransaction>;

  test_balanceUnderlying(overrides?: Overrides): Promise<ContractTransaction>;

  "test_balanceUnderlying()"(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  test_depositAndWithdraw(overrides?: Overrides): Promise<ContractTransaction>;

  "test_depositAndWithdraw()"(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  test_setGovernance(overrides?: Overrides): Promise<ContractTransaction>;

  "test_setGovernance()"(overrides?: Overrides): Promise<ContractTransaction>;

  usdc(overrides?: CallOverrides): Promise<string>;

  "usdc()"(overrides?: CallOverrides): Promise<string>;

  user1(overrides?: CallOverrides): Promise<string>;

  "user1()"(overrides?: CallOverrides): Promise<string>;

  user2(overrides?: CallOverrides): Promise<string>;

  "user2()"(overrides?: CallOverrides): Promise<string>;

  user3(overrides?: CallOverrides): Promise<string>;

  "user3()"(overrides?: CallOverrides): Promise<string>;

  weth(overrides?: CallOverrides): Promise<string>;

  "weth()"(overrides?: CallOverrides): Promise<string>;

  yusdc(overrides?: CallOverrides): Promise<string>;

  "yusdc()"(overrides?: CallOverrides): Promise<string>;

  yusdcAsset(overrides?: CallOverrides): Promise<string>;

  "yusdcAsset()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    IS_TEST(overrides?: CallOverrides): Promise<boolean>;

    "IS_TEST()"(overrides?: CallOverrides): Promise<boolean>;

    _elfDeploy(overrides?: CallOverrides): Promise<string>;

    "_elfDeploy()"(overrides?: CallOverrides): Promise<string>;

    elf(overrides?: CallOverrides): Promise<string>;

    "elf()"(overrides?: CallOverrides): Promise<string>;

    failed(overrides?: CallOverrides): Promise<boolean>;

    "failed()"(overrides?: CallOverrides): Promise<boolean>;

    hevm(overrides?: CallOverrides): Promise<string>;

    "hevm()"(overrides?: CallOverrides): Promise<string>;

    setUp(overrides?: CallOverrides): Promise<void>;

    "setUp()"(overrides?: CallOverrides): Promise<void>;

    testFail_setGovernance(overrides?: CallOverrides): Promise<void>;

    "testFail_setGovernance()"(overrides?: CallOverrides): Promise<void>;

    test_balance(overrides?: CallOverrides): Promise<void>;

    "test_balance()"(overrides?: CallOverrides): Promise<void>;

    test_balanceUnderlying(overrides?: CallOverrides): Promise<void>;

    "test_balanceUnderlying()"(overrides?: CallOverrides): Promise<void>;

    test_depositAndWithdraw(overrides?: CallOverrides): Promise<void>;

    "test_depositAndWithdraw()"(overrides?: CallOverrides): Promise<void>;

    test_setGovernance(overrides?: CallOverrides): Promise<void>;

    "test_setGovernance()"(overrides?: CallOverrides): Promise<void>;

    usdc(overrides?: CallOverrides): Promise<string>;

    "usdc()"(overrides?: CallOverrides): Promise<string>;

    user1(overrides?: CallOverrides): Promise<string>;

    "user1()"(overrides?: CallOverrides): Promise<string>;

    user2(overrides?: CallOverrides): Promise<string>;

    "user2()"(overrides?: CallOverrides): Promise<string>;

    user3(overrides?: CallOverrides): Promise<string>;

    "user3()"(overrides?: CallOverrides): Promise<string>;

    weth(overrides?: CallOverrides): Promise<string>;

    "weth()"(overrides?: CallOverrides): Promise<string>;

    yusdc(overrides?: CallOverrides): Promise<string>;

    "yusdc()"(overrides?: CallOverrides): Promise<string>;

    yusdcAsset(overrides?: CallOverrides): Promise<string>;

    "yusdcAsset()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    eventListener(target: null, exact: null): EventFilter;

    log_bytes32(undefined: null): EventFilter;

    log_named_address(key: null, val: null): EventFilter;

    log_named_bytes32(key: null, val: null): EventFilter;

    log_named_decimal_int(key: null, val: null, decimals: null): EventFilter;

    log_named_decimal_uint(key: null, val: null, decimals: null): EventFilter;

    log_named_int(key: null, val: null): EventFilter;

    log_named_string(key: null, val: null): EventFilter;

    log_named_uint(key: null, val: null): EventFilter;

    logs(undefined: null): EventFilter;
  };

  estimateGas: {
    IS_TEST(overrides?: CallOverrides): Promise<BigNumber>;

    "IS_TEST()"(overrides?: CallOverrides): Promise<BigNumber>;

    _elfDeploy(overrides?: CallOverrides): Promise<BigNumber>;

    "_elfDeploy()"(overrides?: CallOverrides): Promise<BigNumber>;

    elf(overrides?: CallOverrides): Promise<BigNumber>;

    "elf()"(overrides?: CallOverrides): Promise<BigNumber>;

    failed(overrides?: CallOverrides): Promise<BigNumber>;

    "failed()"(overrides?: CallOverrides): Promise<BigNumber>;

    hevm(overrides?: CallOverrides): Promise<BigNumber>;

    "hevm()"(overrides?: CallOverrides): Promise<BigNumber>;

    setUp(overrides?: Overrides): Promise<BigNumber>;

    "setUp()"(overrides?: Overrides): Promise<BigNumber>;

    testFail_setGovernance(overrides?: Overrides): Promise<BigNumber>;

    "testFail_setGovernance()"(overrides?: Overrides): Promise<BigNumber>;

    test_balance(overrides?: Overrides): Promise<BigNumber>;

    "test_balance()"(overrides?: Overrides): Promise<BigNumber>;

    test_balanceUnderlying(overrides?: Overrides): Promise<BigNumber>;

    "test_balanceUnderlying()"(overrides?: Overrides): Promise<BigNumber>;

    test_depositAndWithdraw(overrides?: Overrides): Promise<BigNumber>;

    "test_depositAndWithdraw()"(overrides?: Overrides): Promise<BigNumber>;

    test_setGovernance(overrides?: Overrides): Promise<BigNumber>;

    "test_setGovernance()"(overrides?: Overrides): Promise<BigNumber>;

    usdc(overrides?: CallOverrides): Promise<BigNumber>;

    "usdc()"(overrides?: CallOverrides): Promise<BigNumber>;

    user1(overrides?: CallOverrides): Promise<BigNumber>;

    "user1()"(overrides?: CallOverrides): Promise<BigNumber>;

    user2(overrides?: CallOverrides): Promise<BigNumber>;

    "user2()"(overrides?: CallOverrides): Promise<BigNumber>;

    user3(overrides?: CallOverrides): Promise<BigNumber>;

    "user3()"(overrides?: CallOverrides): Promise<BigNumber>;

    weth(overrides?: CallOverrides): Promise<BigNumber>;

    "weth()"(overrides?: CallOverrides): Promise<BigNumber>;

    yusdc(overrides?: CallOverrides): Promise<BigNumber>;

    "yusdc()"(overrides?: CallOverrides): Promise<BigNumber>;

    yusdcAsset(overrides?: CallOverrides): Promise<BigNumber>;

    "yusdcAsset()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    IS_TEST(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "IS_TEST()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _elfDeploy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "_elfDeploy()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    elf(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "elf()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    failed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "failed()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hevm(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "hevm()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setUp(overrides?: Overrides): Promise<PopulatedTransaction>;

    "setUp()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    testFail_setGovernance(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "testFail_setGovernance()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    test_balance(overrides?: Overrides): Promise<PopulatedTransaction>;

    "test_balance()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    test_balanceUnderlying(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "test_balanceUnderlying()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    test_depositAndWithdraw(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "test_depositAndWithdraw()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    test_setGovernance(overrides?: Overrides): Promise<PopulatedTransaction>;

    "test_setGovernance()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    usdc(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "usdc()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    user1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "user1()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    user2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "user2()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    user3(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "user3()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    weth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "weth()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    yusdc(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "yusdc()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    yusdcAsset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "yusdcAsset()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
