/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ElfDeployInterface extends ethers.utils.Interface {
  functions: {
    "changeGovernance(address)": FunctionFragment;
    "config()": FunctionFragment;
    "elfUsdc()": FunctionFragment;
    "elfWeth()": FunctionFragment;
    "factory()": FunctionFragment;
    "init()": FunctionFragment;
    "usdc()": FunctionFragment;
    "weth()": FunctionFragment;
    "yusdc()": FunctionFragment;
    "yusdcAsset()": FunctionFragment;
    "yweth()": FunctionFragment;
    "ywethAsset()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "changeGovernance",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(functionFragment: "elfUsdc", values?: undefined): string;
  encodeFunctionData(functionFragment: "elfWeth", values?: undefined): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(functionFragment: "init", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;
  encodeFunctionData(functionFragment: "yusdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "yusdcAsset",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "yweth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ywethAsset",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "changeGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "elfUsdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "elfWeth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yusdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yusdcAsset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yweth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ywethAsset", data: BytesLike): Result;

  events: {};
}

export class ElfDeploy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ElfDeployInterface;

  functions: {
    changeGovernance(
      _governance: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "changeGovernance(address)"(
      _governance: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    config(overrides?: Overrides): Promise<ContractTransaction>;

    "config()"(overrides?: Overrides): Promise<ContractTransaction>;

    elfUsdc(overrides?: CallOverrides): Promise<[string]>;

    "elfUsdc()"(overrides?: CallOverrides): Promise<[string]>;

    elfWeth(overrides?: CallOverrides): Promise<[string]>;

    "elfWeth()"(overrides?: CallOverrides): Promise<[string]>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    "factory()"(overrides?: CallOverrides): Promise<[string]>;

    init(overrides?: Overrides): Promise<ContractTransaction>;

    "init()"(overrides?: Overrides): Promise<ContractTransaction>;

    usdc(overrides?: CallOverrides): Promise<[string]>;

    "usdc()"(overrides?: CallOverrides): Promise<[string]>;

    weth(overrides?: CallOverrides): Promise<[string]>;

    "weth()"(overrides?: CallOverrides): Promise<[string]>;

    yusdc(overrides?: CallOverrides): Promise<[string]>;

    "yusdc()"(overrides?: CallOverrides): Promise<[string]>;

    yusdcAsset(overrides?: CallOverrides): Promise<[string]>;

    "yusdcAsset()"(overrides?: CallOverrides): Promise<[string]>;

    yweth(overrides?: CallOverrides): Promise<[string]>;

    "yweth()"(overrides?: CallOverrides): Promise<[string]>;

    ywethAsset(overrides?: CallOverrides): Promise<[string]>;

    "ywethAsset()"(overrides?: CallOverrides): Promise<[string]>;
  };

  changeGovernance(
    _governance: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "changeGovernance(address)"(
    _governance: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  config(overrides?: Overrides): Promise<ContractTransaction>;

  "config()"(overrides?: Overrides): Promise<ContractTransaction>;

  elfUsdc(overrides?: CallOverrides): Promise<string>;

  "elfUsdc()"(overrides?: CallOverrides): Promise<string>;

  elfWeth(overrides?: CallOverrides): Promise<string>;

  "elfWeth()"(overrides?: CallOverrides): Promise<string>;

  factory(overrides?: CallOverrides): Promise<string>;

  "factory()"(overrides?: CallOverrides): Promise<string>;

  init(overrides?: Overrides): Promise<ContractTransaction>;

  "init()"(overrides?: Overrides): Promise<ContractTransaction>;

  usdc(overrides?: CallOverrides): Promise<string>;

  "usdc()"(overrides?: CallOverrides): Promise<string>;

  weth(overrides?: CallOverrides): Promise<string>;

  "weth()"(overrides?: CallOverrides): Promise<string>;

  yusdc(overrides?: CallOverrides): Promise<string>;

  "yusdc()"(overrides?: CallOverrides): Promise<string>;

  yusdcAsset(overrides?: CallOverrides): Promise<string>;

  "yusdcAsset()"(overrides?: CallOverrides): Promise<string>;

  yweth(overrides?: CallOverrides): Promise<string>;

  "yweth()"(overrides?: CallOverrides): Promise<string>;

  ywethAsset(overrides?: CallOverrides): Promise<string>;

  "ywethAsset()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    changeGovernance(
      _governance: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "changeGovernance(address)"(
      _governance: string,
      overrides?: CallOverrides
    ): Promise<void>;

    config(overrides?: CallOverrides): Promise<void>;

    "config()"(overrides?: CallOverrides): Promise<void>;

    elfUsdc(overrides?: CallOverrides): Promise<string>;

    "elfUsdc()"(overrides?: CallOverrides): Promise<string>;

    elfWeth(overrides?: CallOverrides): Promise<string>;

    "elfWeth()"(overrides?: CallOverrides): Promise<string>;

    factory(overrides?: CallOverrides): Promise<string>;

    "factory()"(overrides?: CallOverrides): Promise<string>;

    init(overrides?: CallOverrides): Promise<void>;

    "init()"(overrides?: CallOverrides): Promise<void>;

    usdc(overrides?: CallOverrides): Promise<string>;

    "usdc()"(overrides?: CallOverrides): Promise<string>;

    weth(overrides?: CallOverrides): Promise<string>;

    "weth()"(overrides?: CallOverrides): Promise<string>;

    yusdc(overrides?: CallOverrides): Promise<string>;

    "yusdc()"(overrides?: CallOverrides): Promise<string>;

    yusdcAsset(overrides?: CallOverrides): Promise<string>;

    "yusdcAsset()"(overrides?: CallOverrides): Promise<string>;

    yweth(overrides?: CallOverrides): Promise<string>;

    "yweth()"(overrides?: CallOverrides): Promise<string>;

    ywethAsset(overrides?: CallOverrides): Promise<string>;

    "ywethAsset()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    changeGovernance(
      _governance: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "changeGovernance(address)"(
      _governance: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    config(overrides?: Overrides): Promise<BigNumber>;

    "config()"(overrides?: Overrides): Promise<BigNumber>;

    elfUsdc(overrides?: CallOverrides): Promise<BigNumber>;

    "elfUsdc()"(overrides?: CallOverrides): Promise<BigNumber>;

    elfWeth(overrides?: CallOverrides): Promise<BigNumber>;

    "elfWeth()"(overrides?: CallOverrides): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    "factory()"(overrides?: CallOverrides): Promise<BigNumber>;

    init(overrides?: Overrides): Promise<BigNumber>;

    "init()"(overrides?: Overrides): Promise<BigNumber>;

    usdc(overrides?: CallOverrides): Promise<BigNumber>;

    "usdc()"(overrides?: CallOverrides): Promise<BigNumber>;

    weth(overrides?: CallOverrides): Promise<BigNumber>;

    "weth()"(overrides?: CallOverrides): Promise<BigNumber>;

    yusdc(overrides?: CallOverrides): Promise<BigNumber>;

    "yusdc()"(overrides?: CallOverrides): Promise<BigNumber>;

    yusdcAsset(overrides?: CallOverrides): Promise<BigNumber>;

    "yusdcAsset()"(overrides?: CallOverrides): Promise<BigNumber>;

    yweth(overrides?: CallOverrides): Promise<BigNumber>;

    "yweth()"(overrides?: CallOverrides): Promise<BigNumber>;

    ywethAsset(overrides?: CallOverrides): Promise<BigNumber>;

    "ywethAsset()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    changeGovernance(
      _governance: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "changeGovernance(address)"(
      _governance: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    config(overrides?: Overrides): Promise<PopulatedTransaction>;

    "config()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    elfUsdc(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "elfUsdc()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    elfWeth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "elfWeth()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "factory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    init(overrides?: Overrides): Promise<PopulatedTransaction>;

    "init()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    usdc(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "usdc()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    weth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "weth()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    yusdc(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "yusdc()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    yusdcAsset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "yusdcAsset()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    yweth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "yweth()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ywethAsset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ywethAsset()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
