/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface EmergencyPeriodInterface extends ethers.utils.Interface {
  functions: {
    "getEmergencyPeriod()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getEmergencyPeriod",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getEmergencyPeriod",
    data: BytesLike
  ): Result;

  events: {
    "EmergencyPeriodChanged(bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "EmergencyPeriodChanged"): EventFragment;
}

export class EmergencyPeriod extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: EmergencyPeriodInterface;

  functions: {
    getEmergencyPeriod(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber] & {
        active: boolean;
        endDate: BigNumber;
        checkEndDate: BigNumber;
      }
    >;

    "getEmergencyPeriod()"(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber] & {
        active: boolean;
        endDate: BigNumber;
        checkEndDate: BigNumber;
      }
    >;
  };

  getEmergencyPeriod(
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber, BigNumber] & {
      active: boolean;
      endDate: BigNumber;
      checkEndDate: BigNumber;
    }
  >;

  "getEmergencyPeriod()"(
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber, BigNumber] & {
      active: boolean;
      endDate: BigNumber;
      checkEndDate: BigNumber;
    }
  >;

  callStatic: {
    getEmergencyPeriod(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber] & {
        active: boolean;
        endDate: BigNumber;
        checkEndDate: BigNumber;
      }
    >;

    "getEmergencyPeriod()"(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber] & {
        active: boolean;
        endDate: BigNumber;
        checkEndDate: BigNumber;
      }
    >;
  };

  filters: {
    EmergencyPeriodChanged(active: null): EventFilter;
  };

  estimateGas: {
    getEmergencyPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    "getEmergencyPeriod()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getEmergencyPeriod(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getEmergencyPeriod()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
