/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IElfLenderInterface extends ethers.utils.Interface {
  functions: {
    "balances()": FunctionFragment;
    "depositAndBorrow(uint256)": FunctionFragment;
    "liabilities()": FunctionFragment;
    "repayAndWithdraw(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "balances", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositAndBorrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liabilities",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repayAndWithdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositAndBorrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liabilities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "repayAndWithdraw",
    data: BytesLike
  ): Result;

  events: {};
}

export class IElfLender extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IElfLenderInterface;

  functions: {
    balances(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "balances()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    depositAndBorrow(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "depositAndBorrow(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    liabilities(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "liabilities()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    repayAndWithdraw(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "repayAndWithdraw(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  balances(overrides?: CallOverrides): Promise<BigNumber>;

  "balances()"(overrides?: CallOverrides): Promise<BigNumber>;

  depositAndBorrow(
    arg0: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "depositAndBorrow(uint256)"(
    arg0: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  liabilities(overrides?: CallOverrides): Promise<BigNumber>;

  "liabilities()"(overrides?: CallOverrides): Promise<BigNumber>;

  repayAndWithdraw(
    arg0: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "repayAndWithdraw(uint256)"(
    arg0: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    balances(overrides?: CallOverrides): Promise<BigNumber>;

    "balances()"(overrides?: CallOverrides): Promise<BigNumber>;

    depositAndBorrow(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "depositAndBorrow(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    liabilities(overrides?: CallOverrides): Promise<BigNumber>;

    "liabilities()"(overrides?: CallOverrides): Promise<BigNumber>;

    repayAndWithdraw(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "repayAndWithdraw(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    balances(overrides?: CallOverrides): Promise<BigNumber>;

    "balances()"(overrides?: CallOverrides): Promise<BigNumber>;

    depositAndBorrow(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "depositAndBorrow(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    liabilities(overrides?: CallOverrides): Promise<BigNumber>;

    "liabilities()"(overrides?: CallOverrides): Promise<BigNumber>;

    repayAndWithdraw(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "repayAndWithdraw(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    balances(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "balances()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositAndBorrow(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "depositAndBorrow(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    liabilities(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "liabilities()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    repayAndWithdraw(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "repayAndWithdraw(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
