/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface UserProxyInterface extends ethers.utils.Interface {
  functions: {
    "authorize(address)": FunctionFragment;
    "authorized(address)": FunctionFragment;
    "deauthorize(address)": FunctionFragment;
    "isAuthorized(address)": FunctionFragment;
    "isFrozen()": FunctionFragment;
    "mint(uint256,address,uint256,address)": FunctionFragment;
    "mintPermit(uint256,address,uint256,address,uint8,bytes32,bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "setIsFrozen(bool)": FunctionFragment;
    "weth()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "authorize", values: [string]): string;
  encodeFunctionData(functionFragment: "authorized", values: [string]): string;
  encodeFunctionData(functionFragment: "deauthorize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "isFrozen", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [BigNumberish, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintPermit",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      string,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setIsFrozen",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;

  decodeFunctionResult(functionFragment: "authorize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "authorized", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deauthorize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isFrozen", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintPermit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setIsFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;

  events: {};
}

export class UserProxy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: UserProxyInterface;

  functions: {
    authorize(who: string, overrides?: Overrides): Promise<ContractTransaction>;

    "authorize(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    authorized(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "authorized(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    deauthorize(
      who: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deauthorize(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isAuthorized(
      who: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "isAuthorized(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isFrozen(overrides?: CallOverrides): Promise<[boolean]>;

    "isFrozen()"(overrides?: CallOverrides): Promise<[boolean]>;

    mint(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "mint(uint256,address,uint256,address)"(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    mintPermit(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "mintPermit(uint256,address,uint256,address,uint8,bytes32,bytes32)"(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    setIsFrozen(
      newState: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setIsFrozen(bool)"(
      newState: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    weth(overrides?: CallOverrides): Promise<[string]>;

    "weth()"(overrides?: CallOverrides): Promise<[string]>;
  };

  authorize(who: string, overrides?: Overrides): Promise<ContractTransaction>;

  "authorize(address)"(
    who: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  authorized(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "authorized(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  deauthorize(who: string, overrides?: Overrides): Promise<ContractTransaction>;

  "deauthorize(address)"(
    who: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isAuthorized(
    who: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "isAuthorized(address)"(
    who: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isFrozen(overrides?: CallOverrides): Promise<boolean>;

  "isFrozen()"(overrides?: CallOverrides): Promise<boolean>;

  mint(
    amount: BigNumberish,
    underlying: string,
    expiration: BigNumberish,
    elf: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "mint(uint256,address,uint256,address)"(
    amount: BigNumberish,
    underlying: string,
    expiration: BigNumberish,
    elf: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  mintPermit(
    amount: BigNumberish,
    underlying: string,
    expiration: BigNumberish,
    elf: string,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "mintPermit(uint256,address,uint256,address,uint8,bytes32,bytes32)"(
    amount: BigNumberish,
    underlying: string,
    expiration: BigNumberish,
    elf: string,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  setIsFrozen(
    newState: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setIsFrozen(bool)"(
    newState: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  weth(overrides?: CallOverrides): Promise<string>;

  "weth()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    authorize(who: string, overrides?: CallOverrides): Promise<void>;

    "authorize(address)"(who: string, overrides?: CallOverrides): Promise<void>;

    authorized(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "authorized(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    deauthorize(who: string, overrides?: CallOverrides): Promise<void>;

    "deauthorize(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isAuthorized(who: string, overrides?: CallOverrides): Promise<boolean>;

    "isAuthorized(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isFrozen(overrides?: CallOverrides): Promise<boolean>;

    "isFrozen()"(overrides?: CallOverrides): Promise<boolean>;

    mint(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "mint(uint256,address,uint256,address)"(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      overrides?: CallOverrides
    ): Promise<void>;

    mintPermit(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "mintPermit(uint256,address,uint256,address,uint8,bytes32,bytes32)"(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    setIsFrozen(newState: boolean, overrides?: CallOverrides): Promise<void>;

    "setIsFrozen(bool)"(
      newState: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    weth(overrides?: CallOverrides): Promise<string>;

    "weth()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    authorize(who: string, overrides?: Overrides): Promise<BigNumber>;

    "authorize(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    authorized(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "authorized(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deauthorize(who: string, overrides?: Overrides): Promise<BigNumber>;

    "deauthorize(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isAuthorized(who: string, overrides?: Overrides): Promise<BigNumber>;

    "isAuthorized(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isFrozen(overrides?: CallOverrides): Promise<BigNumber>;

    "isFrozen()"(overrides?: CallOverrides): Promise<BigNumber>;

    mint(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "mint(uint256,address,uint256,address)"(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    mintPermit(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "mintPermit(uint256,address,uint256,address,uint8,bytes32,bytes32)"(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    setIsFrozen(newState: boolean, overrides?: Overrides): Promise<BigNumber>;

    "setIsFrozen(bool)"(
      newState: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    weth(overrides?: CallOverrides): Promise<BigNumber>;

    "weth()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    authorize(
      who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "authorize(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    authorized(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "authorized(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deauthorize(
      who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deauthorize(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isAuthorized(
      who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "isAuthorized(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isFrozen(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isFrozen()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mint(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "mint(uint256,address,uint256,address)"(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    mintPermit(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mintPermit(uint256,address,uint256,address,uint8,bytes32,bytes32)"(
      amount: BigNumberish,
      underlying: string,
      expiration: BigNumberish,
      elf: string,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setIsFrozen(
      newState: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setIsFrozen(bool)"(
      newState: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    weth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "weth()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
