/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { DateString } from "../DateString";

export class DateString__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<DateString> {
    return super.deploy(overrides || {}) as Promise<DateString>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DateString {
    return super.attach(address) as DateString;
  }
  connect(signer: Signer): DateString__factory {
    return super.connect(signer) as DateString__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DateString {
    return new Contract(address, _abi, signerOrProvider) as DateString;
  }
}

const _abi = [
  {
    inputs: [],
    name: "OFFSET19700101",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SECONDS_PER_DAY",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SECONDS_PER_HOUR",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SECONDS_PER_MINUTE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x61018a610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100565760003560e01c80634df861261461005b57806374f0314f14610079578063a3f144ae14610097578063e9556430146100b5575b600080fd5b6100636100d3565b6040516100709190610125565b60405180910390f35b6100816100d9565b60405161008e9190610125565b60405180910390f35b61009f6100e0565b6040516100ac919061010a565b60405180910390f35b6100bd6100e7565b6040516100ca9190610125565b60405180910390f35b610e1081565b6201518081565b62253d8c81565b603c81565b6100f581610140565b82525050565b6101048161014a565b82525050565b600060208201905061011f60008301846100ec565b92915050565b600060208201905061013a60008301846100fb565b92915050565b6000819050919050565b600081905091905056fea2646970667358221220bd8c3ee876de198c4f22b28154490325b734408bfaf2b050bb37f3a295015b1a64736f6c63430008000033";
