name: Test coverage

on: [pull_request]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: npm ci
      - run: npm run test:coverage

      - name: PR comment (lcov)
        uses: vebr/jest-lcov-reporter@v0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: frontend/coverage/lcov.info
