export const MOCK_MARKET_ADDRESSES = [
  "0xETH_FYETH_MARKET_1",
  "0xETH_YCETH_MARKET_1",
  "0xUSDDC_FYUSDC_MARKET_1",
  "0xUSDC_YCUSDC_MARKET_1",
];

export const MOCK_TRANCHE_ADDRESSES = ["0xTRANCHE_ETH_1", "0xTRANCHE_USDC_1"];
export const MOCK_YC_ADDRESSES = ["0xYC_ETH_1", "0xYC_USDC_1"];
export const MOCK_TRANCHE_FACTORY_ADDRESS = "0xTRANCHE_FACTORY";

export const MOCK_ELF_ADDRESSES = ["0xEFL_ETH_1", "0xELF_USDC_1"];

export const ALL_MOCK_ADDRESSES = [
  ...MOCK_MARKET_ADDRESSES,
  ...MOCK_TRANCHE_ADDRESSES,
  MOCK_TRANCHE_FACTORY_ADDRESS,
  ...MOCK_ELF_ADDRESSES,
];
